<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'city', 'county', 'code', 'openId', 'selling_area_name', 'area_name', 'grid_name', 'account_name', 'shop_num', 'assignedShop'];
        }

        return ['__isInitialized__', 'id', 'city', 'county', 'code', 'openId', 'selling_area_name', 'area_name', 'grid_name', 'account_name', 'shop_num', 'assignedShop'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOpenId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenId', []);

        return parent::getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenId($openId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenId', [$openId]);

        return parent::setOpenId($openId);
    }

    /**
     * {@inheritDoc}
     */
    public function assignedToShop(\Shop $shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assignedToShop', [$shop]);

        return parent::assignedToShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function clearShops()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearShops', []);

        return parent::clearShops();
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedShop', []);

        return parent::getAssignedShop();
    }

    /**
     * {@inheritDoc}
     */
    public function getShopNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopNum', []);

        return parent::getShopNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopNum($shop_num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopNum', [$shop_num]);

        return parent::setShopNum($shop_num);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCounty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCounty', []);

        return parent::getCounty();
    }

    /**
     * {@inheritDoc}
     */
    public function setCounty($county)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCounty', [$county]);

        return parent::setCounty($county);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellingAreaName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellingAreaName', []);

        return parent::getSellingAreaName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellingAreaName($selling_area_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellingAreaName', [$selling_area_name]);

        return parent::setSellingAreaName($selling_area_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaName', []);

        return parent::getAreaName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaName($area_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaName', [$area_name]);

        return parent::setAreaName($area_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getGridName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGridName', []);

        return parent::getGridName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGridName($grid_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGridName', [$grid_name]);

        return parent::setGridName($grid_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountName', []);

        return parent::getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountName($account_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountName', [$account_name]);

        return parent::setAccountName($account_name);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
